---
title: "Exposition- obas"
output:
  html_document:
    css: ~/GitHub/cognition-stress-activity/libs/css/sidebar.css
    keep_md: yes
    toc: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

<!-- These two chunks should be added in the beginning of every .Rmd that you want to source an .R script -->
<!--  The 1st mandatory chunck  -->
<!--  Set the working directory to the repository's base directory -->
```{r, echo=F, message=F} 
#Don't combine this call with any other chunk 
# cat("Working directory: ", getwd()) # check where you are
  library(knitr)
# Rmd is in "./reports/reportA/reportA.Rmd", but now the root is "./"
  knitr::opts_knit$set(root.dir='../../../') 
```

<!--  The 2nd mandatory chunck  -->
<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# set options shared by all chunks
opts_chunk$set(
  results='show', 
  message = TRUE,
  comment = NA, 
  tidy = FALSE,
  fig.height = 4, 
  fig.width = 5.5, 
  out.width = "550px",
  fig.path = 'figure_rmd/',     
  dev = "png",
  dpi = 400
  # fig.path = 'figure_pdf/',     
  # dev = "pdf"#,
  # dev.args=list(pdf = list(colormodel = 'cmyk'))
)
C_echo <- TRUE
C_message<- FALSE
C_warning<- FALSE

echoChunks <- FALSE
options(width=120) #So the output is 50% wider than the default.
# connect to the file with the underlying R script  
read_chunk("./sandbox/obas/exposition-1-obas/mmse-obas.R") 
```

```{r load-packages, echo=FALSE, message=C_message, warning=C_warning}
```

```{r load-sources, echo=FALSE, message=C_message, warning=C_warning}
```

# Exposition

## Ellis-Island

Loading the data and renaming the variables

```{r declare-globals, echo=FALSE, message=C_message, warning=C_warning}
```

```{r load-data, echo=FALSE, message=C_message, warning=C_warning}
```


## Tweak Data
```{r tweak-data, echo=FALSE, message=C_message, warning=C_warning, eval=T}
```

## Graphs  
```{r @knitr univariate-quality-check, echo=FALSE, message=C_message, warning=C_warning, eval=T}
```

```{r BasicGraph1, echo=C_echo, message=C_message, warning=C_warning}
```

```{r BasicGraph2, echo=FALSE, message=C_message, warning=C_warning}
```

```{r @knitr multi-variate-quality-check, echo=C_echo, message=C_message, warning=C_warning}
```

```{r graph, echo=FALSE, message=C_message, warning=C_warning}
```


